# Generated by Django 5.1.6 on 2025-03-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=20)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('exit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trade_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
