# Generated by Django 5.1.6 on 2025-03-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='pnl',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
