# Generated by Django 5.1.6 on 2025-03-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
