# Generated by Django 5.1.6 on 2025-03-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtestrun',
            name='parameters',
        ),
    ]
